### ISSUE TITLE
Heap-buffer-overflow READ in ChoiceTheSame

### ISSUE THREAD

**Issue by kcwu** [chewing/libchewing#241]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=84

reduced testcase
```
$ xxd -r > heap-buffer-overflow
00000000: 743d 0621 743d 003d 0600 743d 743d 003d  t=.!t=.=..t=t=.=
00000010: 0600 743d 0006 3d00 0030 1019 1930 0000  ..t=..=..0...0..
00000020: 0000 0000 0005                           ......
```

to reproduce
```
$ ./test/stress -loop 1 -file heap-buffer-overflow -verbose
```

**Comment by czchen** [comment]
```
$ ./test/stress -loop 1 -file heap-buffer-overflow 2>&1| /usr/bin/asan_symbolize
=================================================================
==11855==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000d011 at pc 0x00000048ae04 bp 0x7ffd29ab5d40 sp 0x7ffd29ab54f0
READ of size 18 at 0x60300000d011 thread T0
    #0 0x48ae03 in __interceptor_memcmp.part.68 asan_interceptors.cc.o:?
    #1 0x48ae03 in ?? ??:0
    #2 0x51147e in ChoiceTheSame choice.c:?
    #3 0x51147e in ?? ??:0
    #4 0x50f07b in SetChoiceInfo choice.c:?
    #5 0x50f07b in ?? ??:0
    #6 0x50c7d8 in ChoiceInitAvail ??:?
    #7 0x50c7d8 in ?? ??:0
    #8 0x4f8a9d in chooseCandidate chewingio.c:?
    #9 0x4f8a9d in ?? ??:0
    #10 0x4f6486 in chewing_handle_Down ??:?
    #11 0x4f6486 in ?? ??:0
    #12 0x4ec78b in type_single_keystroke ??:?
    #13 0x4ec78b in ?? ??:0
    #14 0x4ebb48 in main ??:?
    #15 0x4ebb48 in ?? ??:0
    #16 0x7f7387b0d2b0 in __libc_start_main ??:?
    #17 0x7f7387b0d2b0 in ?? ??:0
    #18 0x41b779 in _start ??:?
    #19 0x41b779 in ?? ??:0

0x60300000d011 is located 0 bytes to the right of 17-byte region [0x60300000d000,0x60300000d011)
allocated by thread T0 here:
    #0 0x4b9f00 in calloc ??:?
    #1 0x4b9f00 in ?? ??:0
    #2 0x5296ea in AlcUserPhraseSeq ??:?
    #3 0x5296ea in ?? ??:0
    #4 0x52e61d in UserUpdatePhrase ??:?
    #5 0x52e61d in ?? ??:0
    #6 0x4f7ca3 in chewing_handle_CtrlNum ??:?
    #7 0x4f7ca3 in ?? ??:0
    #8 0x4ec7d7 in type_single_keystroke ??:?
    #9 0x4ec7d7 in ?? ??:0
    #10 0x4ebb48 in main ??:?
    #11 0x4ebb48 in ?? ??:0
    #12 0x7f7387b0d2b0 in __libc_start_main ??:?
    #13 0x7f7387b0d2b0 in ?? ??:0

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/czchen/src/github.com/chewing/libchewing/test/stress+0x48ae03)
Shadow bytes around the buggy address:
  0x0c067fff99b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fd fd
  0x0c067fff99c0: fd fd fa fa fd fd fd fd fa fa fd fd fd fd fa fa
  0x0c067fff99d0: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fd
  0x0c067fff99e0: fa fa 00 00 02 fa fa fa fd fd fd fd fa fa fd fd
  0x0c067fff99f0: fd fd fa fa fd fd fd fd fa fa fd fd fd fd fa fa
=>0x0c067fff9a00: 00 00[01]fa fa fa fd fd fd fd fa fa fd fd fd fd
  0x0c067fff9a10: fa fa fd fd fd fa fa fa fd fd fd fd fa fa fd fd
  0x0c067fff9a20: fd fa fa fa fd fd fd fd fa fa fd fd fd fd fa fa
  0x0c067fff9a30: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fd
  0x0c067fff9a40: fa fa fd fd fd fd fa fa fd fd fd fd fa fa fd fd
  0x0c067fff9a50: fd fa fa fa fd fd fd fd fa fa fd fd fd fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==11855==ABORTING
```

**Comment by kcwu** [comment]
the fix is verified upstream https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=84#c7

**Comment by yan12125** [comment]
Recently lots of security bugs are fixed in libchewing. I guess those test cases should be added to ```test/```?

**Comment by kcwu** [comment]
Yes, we should implement something like https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md#regression-testing suggested.
