### ISSUE TITLE
heap-buffer-overflow read in CheckUserChoose

### ISSUE THREAD

**Issue by kcwu** [chewing/libchewing#242]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=86

reduced testcase
```
$ xxd -r > 86-heap-buffer-overflow
00000000: 3030 743d 0000 0021 0074 3d10 0000 0000  00t=...!.t=.....
00000010: 0d07 743d 0006 3d74 3d                   ..t=..=t=
```

to reproduce
```
$ ./test/stress -stdin -loop 1 -file  86-heap-buffer-overflow 
```

**Comment by czchen** [comment]
Cannot reprocedure with 5c834f1649731e160692acb88957a6b3a342820a. Do I need to use specific compiler flag to build libchewing?

**Comment by kcwu** [comment]
This is my full steps to reproduce with https://github.com/chewing/libchewing/commit/5c834f1649731e160692acb88957a6b3a342820a:
```
./autogen.sh
CC=clang-3.8 CFLAGS=-fsanitize=address ./configure --disable-shared  --without-sqlite3
make clean check
./test/stress -loop 1 -file  86-heap-buffer-overflow
```

Can you reproduce?

**Comment by czchen** [comment]
Found another issue when trying to reprocedure it, see #246.

**Comment by czchen** [comment]
I can reprocedure this issue.

```
$ ./test/stress -loop 1 -stdin < 86-heap-buffer-overflow
=================================================================
==20096==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000ea35 at pc 0x00000048b18d bp 0x7ffe93494f30 sp 0x7ffe934946e0
READ of size 3 at 0x60200000ea35 thread T0
    #0 0x48b18c  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x48b18c)
    #1 0x518ae6  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x518ae6)
    #2 0x512ff7  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x512ff7)
    #3 0x512928  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x512928)
    #4 0x504ba5  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x504ba5)
    #5 0x4f5108  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x4f5108)
    #6 0x4ebe5a  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x4ebe5a)
    #7 0x4eb69a  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x4eb69a)
    #8 0x7fde030172b0  (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #9 0x41b6e9  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x41b6e9)

0x60200000ea35 is located 0 bytes to the right of 5-byte region [0x60200000ea30,0x60200000ea35)
allocated by thread T0 here:
    #0 0x4b9e70  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x4b9e70)
    #1 0x528ada  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x528ada)
    #2 0x52d99d  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x52d99d)
    #3 0x5036c8  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x5036c8)
    #4 0x4f6d14  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x4f6d14)
    #5 0x4ebd03  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x4ebd03)
    #6 0x4eb69a  (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x4eb69a)
    #7 0x7fde030172b0  (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/mnt/disk/home/czchen/src/github.com/chewing/libchewing/test/stress+0x48b18c) 
Shadow bytes around the buggy address:
  0x0c047fff9cf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d10: fa fa fa fa fa fa fa fa fa fa fd fa fa fa fd fa
  0x0c047fff9d20: fa fa fd fa fa fa fd fa fa fa 04 fa fa fa 04 fa
  0x0c047fff9d30: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
=>0x0c047fff9d40: fa fa fd fd fa fa[05]fa fa fa 06 fa fa fa fd fa
  0x0c047fff9d50: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff9d60: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff9d70: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff9d80: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff9d90: fa fa fd fa fa fa 04 fa fa fa 04 fa fa fa 04 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==20096==ABORTING
```

**Comment by czchen** [comment]
Symbolized output as following

```
$ ./test/stress  -loop 1 -file  86-heap-buffer-overflow 2>&1 | /usr/bin/asan_symbolize
=================================================================
==32765==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000ea55 at pc 0x00000048b21d bp 0x7ffcb78c9cb0 sp 0x7ffcb78c9460
READ of size 3 at 0x60200000ea55 thread T0
    #0 0x48b21c in __interceptor_memcmp.part.68 asan_interceptors.cc.o:?
    #1 0x48b21c in ?? ??:0
    #2 0x5196a6 in CheckUserChoose /home/czchen/src/github.com/chewing/libchewing/src/tree.c:167
    #3 0x5196a6 in ?? ??:0
    #4 0x513bb7 in FindInterval /home/czchen/src/github.com/chewing/libchewing/src/tree.c:343 (discriminator 1)
    #5 0x513bb7 in ?? ??:0
    #6 0x5134e8 in Phrasing /home/czchen/src/github.com/chewing/libchewing/src/tree.c:1009
    #7 0x5134e8 in ?? ??:0
    #8 0x505245 in CallPhrasing /home/czchen/src/github.com/chewing/libchewing/src/chewingutil.c:746
    #9 0x505245 in ?? ??:0
    #10 0x4f56b8 in chewing_handle_Default /home/czchen/src/github.com/chewing/libchewing/src/chewingio.c:1602
    #11 0x4f56b8 in ?? ??:0
    #12 0x4ec819 in type_single_keystroke /home/czchen/src/github.com/chewing/libchewing/test/testhelper.c:184
    #13 0x4ec819 in ?? ??:0
    #14 0x4ebc65 in main /home/czchen/src/github.com/chewing/libchewing/test/stress.c:245
    #15 0x4ebc65 in ?? ??:0
    #16 0x7f78ee02f2b0 in __libc_start_main ??:?
    #17 0x7f78ee02f2b0 in ?? ??:0
    #18 0x41b779 in _start ??:?
    #19 0x41b779 in ?? ??:0

0x60200000ea55 is located 0 bytes to the right of 5-byte region [0x60200000ea50,0x60200000ea55)
allocated by thread T0 here:
    #0 0x4b9f00 in calloc ??:?
    #1 0x4b9f00 in ?? ??:0
    #2 0x5296ea in AlcUserPhraseSeq /home/czchen/src/github.com/chewing/libchewing/src/hash.c:34
    #3 0x5296ea in ?? ??:0
    #4 0x52e61d in UserUpdatePhrase /home/czchen/src/github.com/chewing/libchewing/src/userphrase-hash.c:140 (discriminator 1)
    #5 0x52e61d in ?? ??:0
    #6 0x503d68 in AutoLearnPhrase /home/czchen/src/github.com/chewing/libchewing/src/chewingutil.c:635
    #7 0x503d68 in ?? ??:0
    #8 0x4f72c4 in chewing_handle_Enter /home/czchen/src/github.com/chewing/libchewing/src/chewingio.c:910
    #9 0x4f72c4 in ?? ??:0
    #10 0x4ec78b in type_single_keystroke /home/czchen/src/github.com/chewing/libchewing/test/testhelper.c:174
    #11 0x4ec78b in ?? ??:0
    #12 0x4ebb48 in main /home/czchen/src/github.com/chewing/libchewing/test/stress.c:237
    #13 0x4ebb48 in ?? ??:0
    #14 0x7f78ee02f2b0 in __libc_start_main ??:?
    #15 0x7f78ee02f2b0 in ?? ??:0

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/czchen/src/github.com/chewing/libchewing/test/stress+0x48b21c)
Shadow bytes around the buggy address:
  0x0c047fff9cf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9d10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fd fa
  0x0c047fff9d20: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 04 fa
  0x0c047fff9d30: fa fa 04 fa fa fa fd fa fa fa fd fa fa fa fd fa
=>0x0c047fff9d40: fa fa fd fa fa fa fd fd fa fa[05]fa fa fa 06 fa
  0x0c047fff9d50: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff9d60: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff9d70: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff9d80: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff9d90: fa fa fd fa fa fa fd fa fa fa 04 fa fa fa 04 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==32765==ABORTING
```

**Comment by czchen** [comment]
The problematic code is

```
if (memcmp(ueStrSeek(pUserPhraseData->wordSeq, c.from - from),
           selectStr[chno], ueStrNBytes(selectStr[chno], len)))
    break;
```

**Comment by czchen** [comment]
It is possible that the length of `pUserPhraseData->wordSeq` is not long enough for `memcpy`. Especially when `wordSeq` is not a Chinese word.

```
[tree.c:167 CheckUserChoose] crash point: len = 1, c.from = 1, from = 0, pUserPhraseData->wordSeq = 0x60200000ea50, ueStrSeek = 0x60200000ea53
[tree.c:168 CheckUserChoose] crash point: pUserPhraseData->wordSeq = 盎4
[tree.c:169 CheckUserChoose] crash point: pUserPhraseData->phoneSeq[0] = 92, pUserPhraseData->phoneSeq[1] = 92
[tree.c:170 CheckUserChoose] crash point: ueStrNBytes(selectStr[chno], len) = 3
=================================================================
==6024==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000ea55 at pc 0x00000048b21d bp 0x7ffca48264f0 sp 0x7ffca4825ca0
READ of size 3 at 0x60200000ea55 thread T0
```

**Comment by kcwu** [comment]
Just in case you don't know yet, http://rr-project.org/ is very powerful. Happy debugging :)

**Comment by czchen** [comment]
Thanks. I know the tool, but never try it before.

**Comment by kcwu** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=86 also verified the fix
